"""
Token class represents lexical token generated by scanner
"""
import abc
from typing import Union


class Token(abc.ABC):

    def __init__(self, lexeme: str, name: str):
        self.lexeme: str = lexeme
        self.name: str = name
        self.position: Union[int, None] = None
        self.inserted = False

    def replace_self(self, code: str) -> str:
        # lexm = self.lexeme
        # try1 = code.replace(lexm, '')
        return code.replace(self.lexeme, '', 1)

    def set_position(self, line_num: int):
        self.position = line_num

    def tok_str(self) -> str:
        self.inserted = True
        return f'[{self.name}, {self.lexeme}, {self.position if self.position is not None else "Position unassigned"}]'

    def was_inserted(self) -> bool:
        return self.inserted

    def __len__(self):
        return len(self.lexeme)

    @staticmethod
    def match(code: str) -> bool:
        ...
